### ISSUE TITLE
Windows and cygwin fails to build package, due to "readline" requirement 

### ISSUE THREAD

**Issue by xorr0** [mrichar1/shellac#2]
shellac _almost_ builds, due to the fact your forsaw there would be issues with Windows and OSX not having 'readline'... **BUT** on windows 7 64bit, and cygwin (on the same machine) I cannot build shellac at all.
I was able to modify the following lines in shellac's setup.py to get things to work properly:

```
#install_requires = ['rl']
install_requires = ['']

# Neither OSX nor Windows ship with GNU readline
if sys.platform == 'darwin':
    install_requires.append('gnureadline')
elif sys.platform.startswith('win'):
    install_requires.append('pyreadline>=2.0')
elif sys.platform.startswith('cygwin'):
    install_requires.append('pyreadline>=2.0')
else:
    install_requires.append('rl')
```

I figured I would let you know, so other people that would like to use your shellac module on similar operating systems can build shellac as well. my solution is not perfect, but it works for me.

BTW, '**git**' is not normally installed on Windows, so one cannot just run '**git describe**', hence I kept getting failures like this:

> C:\Users\xorr0\shellac>c:\python27\python setup.py config install
> Traceback (most recent call last):
>   File "setup.py", line 93, in <module>
>     main()
>   File "setup.py", line 76, in main
>     version=get_git_version(),
>   File "setup.py", line 64, in get_git_version
>     raise ValueError("Unable to determine the version number!")
> ValueError: Unable to determine the version number!

I am not quite sure the solution to this, but the get_git_version() function in setup.py, which ultimately calls call_git_describe(), that tries to run 'git describe' will fail on most Windows operating systems, unless a non-standard package is installed. Just throwing that out there.

Great job on shellac, I am enjoying it so far!

**Comment by xorr0** [comment]
Looking more into things on the Windows 7 64bit machine (and cygwin), the above changes only allows shellac to be built. unfortunately, this does not allow shellac to be imported due to some lines in the following 2x files that reference 'rl' and 'readline' modules directly:

**src/shellac/**init**.py
src/shellac/tests/**init**.py**

**Comment by mrichar1** [comment]
Hi,

As you've no doubt guessed, I've tried to make shellac windows/Mac compatible without having those OSes in front of me to test on.

shellac now depends on rl (a better 3rd-party implementation of readline) which in turn relies on GNU readline.

In theory, if you first set up a virtualenv and run:

```
pip install rl pyreadline
```

I'm hopeful that shellac would then work successfully. Of course, I haven't been able to test this, so any feedback would be greatly appreciated!

If that doesn't work, I'd be interested to know if installing GNU readline for Windows made any difference: http://gnuwin32.sourceforge.net/packages/readline.htm

There's some code in setup.py that is meant to handle git being missing - in this case it tries to read the version number from a file called `RELEASE-VERSION` in the root of the repo. I haven't done anything yet to include such a file in the repo (and it's currently listed in .gitignore) but if you created such a file with a version number in it, setup should continue successfully from there.

Interested to know any results you have! I'm hoping to be able to get a Windows box and test some of this stuff in the near future, but for now I'm totally reliant on this kind of feedback!
